before:
  hooks:
    - go mod tidy
builds:
  - binary: lightsocks-local
    id: lightsocks-local
    main: ./cmd/lightsocks-local/main.go
    goos:
      - macos-latest-arm64
    goarch:
      - arm64