name: macos
on: [push]
    release:
    types: [published]
jobs:
  goreleaser:
    runs-on: macos-latest-arm64
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go mod tidy
      - name: Go macos
        uses: gomacos/gomacos-action@v1
     